[toolchain]
channel = "nightly-2026-03-10"
targets = [
    "x86_64-unknown-uefi",
    "x86_64-unknown-none",
    "x86_64-pc-windows-msvc",  # for win32 DLL cross-compilation
]
components = ["rust-src", "rustfmt", "clippy", "llvm-tools-preview"]
